### ISSUE TITLE
map files is not transferred into pipe

### ISSUE THREAD

**Issue by dlebedynskyi** [parroit/gulp-pure-cjs#4]
It seems that source map file is not transferred into the stream. Setting map attribute to true does not make any difference. Running pure-cjs manually with -m flag works correct and produces out.js with out.js.map files.

**Comment by parroit** [comment]
You're welcome... I've changed README to include some info about sourcemaps. 
Do you think it is clear enough now?

**Comment by dlebedynskyi** [comment]
Looks great!

**Comment by parroit** [comment]
Thank you!
